-- Generated by scripts/schema-audit.mjs. Review before running.
-- Run: node scripts/schema-audit.mjs (with DATABASE_URL in .env.local) to regenerate this file.

-- DROP unwanted tables (half-created / legacy).
-- No unwanted tables to drop.

-- ALTER: add missing columns (idempotent).
-- No missing columns to add.

-- If expected tables are missing, run db/migrations 001-011 in order.
